This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file ./flow.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file flow.acn....done (64 entries accepted, 0 rejected).
Sorting entries....done (446 comparisons).
Generating output file flow.acr....done (85 lines written, 0 warnings).
Output written in flow.acr.
Transcript written in flow.alg.
